apiVersion: v1
kind: Secret
metadata:
  name: springboot-app-secret
  namespace: springboot-vue-demo
type: Opaque
data:
  db-password: dXNlcjEyMzQ=
  redis-password: cmVkaXMxMjM0
  jwt-secret: anN0LXNlY3JldC1rZXk=
